export const featuredSubreddits = [
  { url: "nasa" },
  { url: "space" },
  { url: "spaceporn" },
  { url: "esa" },
  { url: "iss" },
  { url: "spacex" },
  { url: "spaceflight" },
  { url: "astronomy" },
  { url: "cosmology" },
  { url: "futurology" },
  { url: "telescopes" },
  { url: "askastronomy" },
  { url: "spaceexploration" },
  { url: "moon" },
  { url: "mars" },
  { url: "curiosityrover" },
  { url: "spacevideos" },
  { url: "spaceflightporn" },
  { url: "astrophotography" },
];
